spring:
  application:
    name: alert-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5434/alerts
    username: postgres
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: alertingEvent:com.enerlytics.events.AlertingEvent

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8084

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus