spring:
  application:
    name: insight-service

  ai:
    ollama:
      chat:
        options:
          model: qwen2.5-coder:0.5b
      init:
        pull-model-strategy: never

usage-service:
  base-url: http://localhost:8083/api/v1/usages

server:
  port: 8085

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
