ALTER TABLE devices
    ADD COLUMN version    BIGINT                       NOT NULL DEFAULT 0,
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_devices_user_id ON devices (user_id);
